#!/bin/bash
for dir; do
    name=$(basename "$dir")
    (
        set -e
        cd "$dir"
        vagrant box update
        vagrant up
        vagrant package --output "$name".box
        vagrant box add --force "$name" "$name".box
        vagrant destroy --force
        rm -f "$name".box
    )
done

