- name: CentOS
  when: ansible_distribution == "CentOS"
  block:

    - name: Query version of centos-stream-repos
      shell: "rpm -q --queryformat='%{VERSION}\n' centos-stream-repos || :"
      args:
        warn: False
      register: centos_stream_repos_version
      changed_when: False

    - name: Repos for Stream
      when: centos_stream_repos_version.stdout|int > 0
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["CentOS-Stream-AppStream", "appstream"]
        - ["CentOS-Stream-PowerTools", "powertools"]
        - ["CentOS-Stream-Extras", "extras"]

- name: Rocky
  when: ansible_distribution == "Rocky"
  block:

    - name: Repos
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["Rocky-AppStream", "appstream"]
        - ["Rocky-PowerTools", "powertools"]
        - ["Rocky-Extras", "extras"]

- name: AlmaLinux
  when: ansible_distribution == "AlmaLinux"
  block:

    - name: Repos
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["almalinux", "appstream"]
        - ["almalinux-powertools", "powertools"]
        - ["almalinux", "extras"]
