---
- name: Install epel repo (not Amazon)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  when: ansible_distribution != "Amazon"

- name: Install epel7 repo (Amazon2)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Maybe install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=present
  when: ansible_distribution_major_version|int < 8

- name: Install shadow-utils
  yum: name=shadow-utils state=latest

- name: User namespaces on CentOS 7
  when: ansible_distribution_major_version|int < 8
  block:

    - name: Set user.max_user_namespaces
      sysctl:
        name: user.max_user_namespaces
        value: "10000"
        sysctl_set: true
        state: present
        reload: true

    - name: Add subuids for vagrant
      lineinfile:
        path: /etc/subuid
        regexp: '^vagrant:'
        line: vagrant:100000:65536

    - name: Add subgids for vagrant
      lineinfile:
        path: /etc/subgid
        regexp: '^vagrant:'
        line: vagrant:100000:65536


- name: CentOS 8 repos
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  block:

    - name: Query version of centos-stream-repos
      shell: "rpm -q --queryformat='%{VERSION}\n' centos-stream-repos || :"
      args:
        warn: False
      register: centos_stream_repos_version
      changed_when: False

    - name: Repos for Stream
      when: centos_stream_repos_version.stdout|int > 0
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["CentOS-Stream-AppStream", "appstream"]
        - ["CentOS-Stream-PowerTools", "powertools"]
        - ["CentOS-Stream-Extras", "extras"]

    - name: Repos for not Stream
      when: not centos_stream_repos_version.stdout|int > 0
      block:

        - name: Repos for 8.2 or lower
          when: ansible_distribution_version|float < 8.3
          ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-AppStream", "AppStream"]
            - ["CentOS-PowerTools", "PowerTools"]
            - ["CentOS-Extras", "extras"]

        - name: Repos for 8.3 and up
          when: ansible_distribution_version|float >= 8.3
          ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-Linux-AppStream", "appstream"]
            - ["CentOS-Linux-PowerTools", "powertools"]
            - ["CentOS-Linux-Extras", "extras"]
