---
- name: Install epel repo (not Amazon)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  when: ansible_distribution != "Amazon"

- name: Install epel7 repo (Amazon2)
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: Maybe install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=present
  when: ansible_distribution_major_version|int < 8

- name: Install shadow-utils
  yum: name=shadow-utils state=latest

- name: User namespaces on CentOS 7
  when: ansible_distribution_major_version|int < 8
  block:

    - name: Set user.max_user_namespaces
      sysctl:
        name: user.max_user_namespaces
        value: "10000"
        sysctl_set: true
        state: present
        reload: true

    - name: Add subuids for vagrant
      lineinfile:
        path: /etc/subuid
        regexp: '^vagrant:'
        line: vagrant:100000:65536

    - name: Add subgids for vagrant
      lineinfile:
        path: /etc/subgid
        regexp: '^vagrant:'
        line: vagrant:100000:65536

- name: ntpdate on CentOS 7
  when: ansible_distribution_major_version == "7"
  block:
    - name: Install ntpdate
      yum:
        name: ntpdate
        state: present

    - name: Enable ntpdate
      service:
        name: ntpdate
        enabled: yes
        state: started

- import_tasks: 8.yml
  when: ansible_distribution_major_version == "8"
