---
- name: Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present

- name: Maybe install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=present
  when: ansible_distribution_major_version|int < 8

- name: CentOS 8 repos
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
  block:

    - name: Query centos-stream-repos
      shell: "rpm -q centos-stream-repos"
      ignore_errors: True
      register: centos_stream_repos
      changed_when: False

    - name: Repos for Stream
      when: centos_stream_repos.rc == 0
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["CentOS-Stream-AppStream", "appstream"]
        - ["CentOS-Stream-PowerTools", "powertools"]
        - ["CentOS-Stream-Extras", "extras"]

    - name: Repos for not Stream
      when: centos_stream_repos.rc != 0
      block:

        - name: Repos for 8.2 or lower
          when: ansible_distribution_version|float < 8.3
          ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-AppStream", "AppStream"]
            - ["CentOS-PowerTools", "PowerTools"]
            - ["CentOS-Extras", "extras"]

        - name: Repos for 8.3 and up
          when: ansible_distribution_version|float >= 8.3
          ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-Linux-AppStream", "appstream"]
            - ["CentOS-Linux-PowerTools", "powertools"]
            - ["CentOS-Linux-Extras", "extras"]
