---
- name: Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  when: ansible_distribution != "Fedora"

- name: Install helpful software
  yum:
    state: present
    name:
      - gdb
      - git
      - git-svn
      - make
      - mc
      - subversion
      - tmux
      - vim-enhanced
      - yum-utils
      - zsh

- name: Check out utils from my repo
  git:
    repo: https://pages.cs.wisc.edu/~matyas/utils.git
    dest: /usr/local/bin/utils
    # http transport does not support `depth`
    #depth: 1

- name: Add utils to path
  copy:
    src: utils.sh
    dest: /etc/profile.d/utils.sh
    owner: root
    group: root
    mode: 644

- name: Check out shell dotfiles
  git:
    repo: https://pages.cs.wisc.edu/~matyas/newshell.git
    dest: /usr/local/share/newshell
    # http transport does not support `depth`
    #depth: 1

- name: Install shell dotfiles
  command: /usr/local/share/newshell/install.sh {{ item }}
  args:
    creates: "{{ item }}/.zshrc"
  with_items:
    - /root
    - /home/vagrant

- name: Use zsh
  user: name={{ item }} shell=/bin/zsh
  with_items:
    - root
    - vagrant

