---
- name: Install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  when: ansible_distribution != "Fedora"

- name: Install helpful software
  yum: name={{ item }} state=present
  with_items:
    - emacs-nox
    - gdb
    - git
    - git-svn
    - make
    - mc
    - rcs
    - subversion
    - tmux
    - vim-enhanced
    - yum-utils
    - yum-fastestmirror
    - zsh

- name: Check out utils from my repo
  git: repo=https://git.doit.wisc.edu/MATYAS/newutils.git
    # repo=http://pages.cs.wisc.edu/~matyas/utils.git
       dest=/usr/local/bin/utils

- name: Add utils to path
  copy: src=utils.sh
        dest=/etc/profile.d/utils.sh
        owner=root
        group=root
        mode=644

- name: Check out shell dotfiles
  git: repo=https://git.doit.wisc.edu/MATYAS/newshell.git
    # repo=http://pages.cs.wisc.edu/~matyas/newshell.git
       dest=/usr/local/share/newshell

- name: Install shell dotfiles
  command: /usr/local/share/newshell/install.sh {{ item }}
  args:
    creates: "{{ item }}/.zshrc"
  with_items:
    - /root
    - /home/vagrant

- name: Use zsh
  user: name={{ item }} shell=/bin/zsh
  with_items:
    - root
    - vagrant

