---
#- when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux", "Scientific"]
- when: ansible_os_family == "RedHat"
  include_role: name=rhel

- name: Install common helpful software
  package:
    state: present
    name:
      - ed
      - gdb
      - git
      - git-svn
      - make
      - mc
      - subversion
      - tmux
      - zsh

- name: yum install helpful software
  yum:
    state: present
    name:
      - vim-enhanced
      - yum-utils
  when: ansible_os_family == "RedHat"

- name: Install libselinux-python
  yum:
    state: present
    name:
      - libselinux-python
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- file:
    state: directory
    path: /usr/local/bin/utils
    owner: root
    group: root
    mode: "755"

- name: Download my utils
  unarchive:
    src: https://git.doit.wisc.edu/MATYAS/publicutils/-/archive/master/publicutils-master.tar.gz
    dest: /usr/local/bin/utils
    remote_src: yes
    validate_certs: "{{ ansible_distribution_major_version == '6' | ternary('no', 'yes') }}"
    extra_opts:
      - --strip-components=1

- name: Add utils to path
  copy:
    src: utils.sh
    dest: /etc/profile.d/utils.sh
    owner: root
    group: root
    mode: "644"

- file:
    state: directory
    path: /usr/local/share/newshell
    owner: root
    group: root
    mode: "755"

- name: Download my shell dotfiles
  unarchive:
    src: https://git.doit.wisc.edu/MATYAS/newshell/-/archive/master/newshell-master.tar.gz
    dest: /usr/local/share/newshell
    remote_src: yes
    validate_certs: "{{ ansible_distribution_major_version == '6' | ternary('no', 'yes') }}"
    extra_opts:
      - --strip-components=1

- name: Install shell dotfiles
  command: /usr/local/share/newshell/install.sh {{ item }}
  args:
    creates: "{{ item }}/.zshrc"
  with_items:
    - /root
    - /home/vagrant

- name: Use zsh
  user: name={{ item }} shell=/bin/zsh
  with_items:
    - root
    - vagrant

