---
# vv Alma's ansible_os_family is RedHat
- when: ansible_os_family in ["RedHat", "Rocky"]
  include_role: name=rhel

- name: Install common helpful software
  package:
    state: present
    name:
      - ed
      - gdb
      - git
      - git-svn
      - make
      - mc
      - subversion
      - tmux
      - unzip
      - zip
      - zsh

- name: yum install helpful software
  yum:
    state: present
    name:
      - vim-enhanced
      - yum-utils
  when: ansible_os_family in ["RedHat", "Rocky"]

- file:
    state: directory
    path: /usr/local/bin/utils
    owner: root
    group: root
    mode: "755"

- name: Download my utils with git
  git:
    repo: 'https://git.doit.wisc.edu/MATYAS/publicutils.git'
    dest: /usr/local/bin/utils
    accept_hostkey: yes

- name: Add utils to path
  copy:
    src: utils.sh
    dest: /etc/profile.d/utils.sh
    owner: root
    group: root
    mode: "644"

- file:
    state: directory
    path: /usr/local/share/newshell
    owner: root
    group: root
    mode: "755"

- name: Download my shell dotfiles with git
  git:
    repo: 'https://git.doit.wisc.edu/MATYAS/newshell.git'
    dest: /usr/local/share/newshell
    accept_hostkey: true

- name: Install shell dotfiles
  command: /usr/local/share/newshell/install.sh {{ item }}
  args:
    creates: "{{ item }}/.zshrc"
  with_items:
    - /root
    - /home/vagrant

- name: Download tmuxrc
  get_url:
    url: https://pages.cs.wisc.edu/~matyas/tmux-inner.conf
    dest: /etc/tmux.conf
    validate_certs: "{{ ansible_distribution_major_version == '7' | ternary('false', 'true') }}"

- name: Fix home dir permissions of vagrant user
  shell:
    cmd: "chown -R vagrant: ~vagrant"

- name: Use zsh
  user: name={{ item }} shell=/bin/zsh
  with_items:
    - root
    - vagrant

