---
- hosts: 127.0.0.1
  remote_user: root
  become: yes
  tasks:

  - name: install dnsmasq
    yum: name=dnsmasq state=present

  - name: edit dnsmasq.conf
    lineinfile:
      dest: /etc/dnsmasq.conf
      line: "listen-address=127.0.0.1"

  - name: add external ip to hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ ansible_default_ipv4.address }}"
      line: "{{ ansible_default_ipv4.address }}  {{ ansible_fqdn }}"

  - name: configure NetworkManager
    ini_file: dest=/etc/NetworkManager/NetworkManager.conf
              section=main
              option=dns
              value=dnsmasq
    when: ansible_distribution_major_version|int >= 7
    notify: restart NetworkManager

  - block:
    - name: configure dhclient
      lineinfile:
        dest: /etc/dhclient.conf
        line: "prepend domain-name-servers 127.0.0.1;"

    - name: start dnsmasq
      service:
        name: dnsmasq
        enabled: yes
        state: started

    - name: run dhclient
      command: dhclient

    when: ansible_distribution_major_version|int == 6


  handlers:

  - name: restart NetworkManager
    service: name=NetworkManager state=restarted

