---
#- name: Install epel repo
#  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm  state=present

#- name: Install yum-plugin-priorities
#  yum: name=yum-plugin-priorities  state=present

- name: Enable PowerTools (8.2 or lower)
  ini_file:
    path: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: "1"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and ansible_distribution_version < "8.3"

- name: Enable PowerTools (8.3 and up)
  ini_file:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    section: powertools
    option: enabled
    value: "1"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and ansible_distribution_version >= "8.3"

- name: Add Condor repository
  yum_repository:
      name: htcondor
      description: Condor {{series}} repository
      gpgkey: "https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor"
      baseurl: "https://research.cs.wisc.edu/htcondor/yum/{{ series }}/rhel{{ ansible_distribution_major_version }}"
      gpgcheck: 1
      priority: "90"


- name: Install Condor
  yum:
      name: condor
      state: latest

