- name: CentOS
  when: ansible_distribution == "CentOS"
  block:

    - name: Query version of centos-stream-repos
      shell: "rpm -q --queryformat='%{VERSION}\n' centos-stream-repos || :"
      args:
        warn: False
      register: centos_stream_repos_version
      changed_when: False

    - name: Repos for Stream
      when: centos_stream_repos_version.stdout|int > 0
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["CentOS-Stream-AppStream", "appstream"]
        - ["CentOS-Stream-PowerTools", "powertools"]
        - ["CentOS-Stream-Extras", "extras"]

    - name: Repos for not Stream
      when: not centos_stream_repos_version.stdout|int > 0
      block:

        - name: Repos for 8.2 or lower
          when: ansible_distribution_version|float < 8.3
          community.general.ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-AppStream", "AppStream"]
            - ["CentOS-PowerTools", "PowerTools"]
            - ["CentOS-Extras", "extras"]

        - name: Repos for 8.3 and up
          when: ansible_distribution_version|float >= 8.3
          community.general.ini_file:
            path: "/etc/yum.repos.d/{{ item[0] }}.repo"
            section: "{{ item[1] }}"
            option: "enabled"
            value: "1"
            create: no
          with_list:
            - ["CentOS-Linux-AppStream", "appstream"]
            - ["CentOS-Linux-PowerTools", "powertools"]
            - ["CentOS-Linux-Extras", "extras"]

- name: Rocky
  when: ansible_distribution == "Rocky"
  block:

    - name: Repos
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["Rocky-AppStream", "appstream"]
        - ["Rocky-PowerTools", "powertools"]
        - ["Rocky-Extras", "extras"]

- name: AlmaLinux
  when: ansible_distribution == "AlmaLinux"
  block:

    - name: Repos
      community.general.ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["almalinux", "appstream"]
        - ["almalinux-powertools", "powertools"]
        - ["almalinux", "extras"]
