- name: AlmaLinux
  when: ansible_distribution == "AlmaLinux"
  block:

    - name: Repos
      ini_file:
        path: "/etc/yum.repos.d/{{ item[0] }}.repo"
        section: "{{ item[1] }}"
        option: "enabled"
        value: "1"
        create: no
      with_list:
        - ["almalinux-appstream", "appstream"]
        - ["almalinux-crb", "crb"]
        - ["almalinux-extras", "extras"]
