---
- name: Install buildah, podman and required deps
  yum:
    state: latest
    name:
      - buildah
      - podman
      - podman-docker
      - shadow-utils
#- name: Set user.max_user_namespaces
#  sysctl:
#    name: user.max_user_namespaces
#    value: "10000"
#    sysctl_set: true
#    state: present
#    reload: true
#
#- name: Add subuids for vagrant
#  lineinfile:
#    path: /etc/subuid
#    regexp: '^vagrant:'
#    line: vagrant:100000:65536
#
#- name: Add subgids for vagrant
#  lineinfile:
#    path: /etc/subgid
#    regexp: '^vagrant:'
#    line: vagrant:100000:65536

