---
- name: include rhel
  include_role: name=rhel

- name: Get package facts
  package_facts: manager=auto

- name: Bootstrap osg-release (pre-23)
  # Download osg-release from repo.opensciencegrid.org if it's not installed or if it's
  # the wrong version. This can't be done with the yum module because it
  # doesn't handle the downgrading properly.

  # rpm --force allows downgrading. Immediately clear the yum cache to keep yum
  # from installing RPMs from the previous OSG repos if upgrading/downgrading
  shell: "rpm -U --force {{ rpmpath|quote }} && yum clean all"
  when: >
    osgver|float < 3.7
    and (
      not 'osg-release' in ansible_facts.packages
      or ansible_facts.packages['osg-release'][0].version != osgver|string
    )

- name: Bootstrap osg-release (23+)
  # Download osg-release from repo.opensciencegrid.org if it's not installed or if it's
  # the wrong version. This can't be done with the yum module because it
  # doesn't handle the downgrading properly.

  # rpm --force allows downgrading. Immediately clear the yum cache to keep yum
  # from installing RPMs from the previous OSG repos if upgrading/downgrading
  shell: "rpm -U --force {{ rpmpath2|quote }} && yum clean all"
  when: >
    osgver|float > 3.7
    and (
      not 'osg-release' in ansible_facts.packages
      or ansible_facts.packages['osg-release'][0].version != osgver|string
    )

- name: Update osg-release
  yum: name=osg-release  state=latest

- name: Import signing key(s)
  shell: "rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG*"
  changed_when: false

- name: Add mock group
  group: name=mock

- name: Add vagrant user to mock group
  user: name=vagrant  groups=mock  append=yes

- name: Add my repos
  yum_repository:
    name: matyas
    description: My yum repo
    baseurl: "https://pages.cs.wisc.edu/~matyas/yum/el{{ ansible_distribution_major_version }}"
    gpgcheck: false
    enabled: false
    priority: "2"
    keepcache: "0"
    metadata_expire: "60"
  when: "ansible_distribution_major_version|int < 10"

- name: Install Python3 and Make
  yum:
    state: present
    name:
      - python3
      - make

- name: Download osg-ca-generator with git
  git:
    version: "master"
    repo: 'https://github.com/opensciencegrid/osg-ca-generator'
    dest: /usr/local/src/osg-ca-generator
    accept_hostkey: true

- name: Install osg-ca-generator
  make:
    chdir: '/usr/local/src/osg-ca-generator'
    target: 'install'
  when: "ansible_distribution_major_version|int < 10"

- name: Add run-cagen
  copy:
    src: run-cagen
    dest: /usr/local/bin/run-cagen
    owner: root
    group: root
    mode: "755"
