---
- include_role: name=rhel

- name: Query version of osg-release
  shell: "rpm -q --queryformat='%{VERSION}\n' osg-release || :"
  args:
    warn: False
  register: osg_release_version
  changed_when: False

- name: Bootstrap osg-release
  # Download osg-release from repo.opensciencegrid.org if it's not installed or if it's
  # the wrong version. This can't be done with the yum module because it
  # doesn't handle the downgrading properly.

  # rpm --force allows downgrading. Immediately clear the yum cache to keep yum
  # from installing RPMs from the previous OSG repos if upgrading/downgrading
  shell: "rpm -U --force {{ rpmpath|quote }} && yum clean all"
  args:
    warn: False
  when: osg_release_version.stdout != osgver|string

- name: Update osg-release
  yum: name=osg-release  state=latest

- name: Import signing key(s)
  shell: "rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-OSG*"
  args:
    warn: False
  changed_when: False

- name: Add mock group
  group: name=mock

- name: Add vagrant user to mock group
  user: name=vagrant  groups=mock  append=yes

- name: Add my repos
  yum_repository:
    name: matyas
    description: My yum repo
    baseurl: "https://pages.cs.wisc.edu/~matyas/yum/el{{ ansible_distribution_major_version }}"
    gpgcheck: no
    enabled: no
    priority: "2"
    keepcache: "0"
    metadata_expire: "60"

- name: Install Python3 and Make
  yum:
    state: present
    name:
      - python3
      - make

- name: Download osg-ca-generator with git
  git:
    repo: 'https://github.com/opensciencegrid/osg-ca-generator'
    dest: /usr/local/share/osg-ca-generator
    accept_hostkey: yes

- name: Install osg-ca-generator
  shell: "cd /usr/local/share/osg-ca-generator && make install"
