---
- name: install dnsmasq
  yum: name=dnsmasq state=present

- name: edit dnsmasq.conf
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: "listen-address=127.0.0.1"

- name: add external ip to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }}  {{ ansible_fqdn }}"

- name: start dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: started

- name: configure dhclient
  lineinfile:
    dest: /etc/dhclient.conf
    line: "prepend domain-name-servers 127.0.0.1;"
    create: yes

- name: run dhclient
  command: dhclient

